package com.example.insightsXmicroservice.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * JPA Entity representing the 'users' table in the PostgreSQL database.
 * This class maps the database columns to Java fields.
 * The primary key is 'user_id' (text).
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    // Primary Key: user_id (TEXT, not bigint ID)
    @Id
    @Column(name = "user_id")
    private String userId;

    // Field used in DTO mapping
    @Column(name = "phone_number", unique = true, nullable = false)
    private String phoneNumber;

    // Field used in DTO mapping
    @Column(name = "full_name")
    private String fullName;

    // Field used in DTO mapping
    @Column(name = "gender")
    private String gender;

    // --- Other necessary table columns for accurate JPA mapping ---

    @Column(name = "phone_number_hash")
    private String phoneNumberHash;

    @Column(name = "date_of_birth")
    private String dateOfBirth;

    @Column(name = "pan_number")
    private String panNumber;

    @Column(name = "is_verified")
    private Boolean isVerified;

    @Column(name = "created_at")
    private Long createdAt;

    @Column(name = "last_login_at")
    private Long lastLoginAt;

    @Column(name = "privacy_consent_given")
    private Boolean privacyConsentGiven;

    @Column(name = "basic_details_completed")
    private Boolean basicDetailsCompleted;

    @Column(name = "credit_score")
    private Integer creditScore;

    // We omit the 'id bigint generated by default as identity' column
    // since the 'user_id' is defined as the primary key constraint in your schema.
}
